handle = "example-us"
label = "example.com"
icon = "example-channel-icon.svg"

[capabilities]
bundles = true
digitalProducts = true
subscriptions = false
variantModel = "products"
multiLocationInventory = true

[requirements]
webpresence = false
orderInsertion = true

[[countries]]
code = "US"
languages = [
  "en"
]
currency = "USD"